In [3]:
import numpy as np

In [54]:
val = np.array([[1,2,-1],[2,3,-1],[1,2,1]])

In [220]:
def VotedPerceptron(array, epoch=1):
    n = array.shape[1]
    w = np.zeros(n-1)
    b = 0
    c = 0
    ans = []
    for t in range(epoch):
        for x in array:
            y_pred = np.dot(x[:-1],w) + b
            if y_pred * x[-1] > 0:
                c = c + 1
            elif c != 0:
                ret = (np.copy(w), b, c)
                ans.append(ret)
                w += x[:-1] * x[-1]
                b += x[-1]
                c = 1
            else:
                c += 1
                w += x[:-1] * x[-1]
                b += x[-1]
        ans.append((np.copy(w),b,c))
    return ans
    
    
def predictVoted(model, data):
    val = 0
    for m in model:
        val += m[2]*np.sign(np.dot(m[0],data)+m[1]-0.00001)
    return np.sign(val-0.00001)

model = VotedPerceptron(val)
predictVoted(model, [1,2])

-1.0

In [205]:
def VanillaPerceptron(array, epoch=1):
    n = array.shape[1]
    w = np.zeros(n-1)
    b = 0
    for t in range(epoch):
        for x in array:
            y_pred = np.dot(x[:-1],w) + b
            if y_pred * x[-1] > 0:
                pass
            else:
                w += x[:-1] * x[-1]
                b += x[-1]
    return (np.copy(w),b)
    
    
def predictVanilla(model, data):
    val = np.sign(np.dot(model[0],data)+model[1])
    return np.sign(val-0.00001)

model = VanillaPerceptron(val)
predictVanilla(model, [1,2])

-1.0

In [231]:
import pandas as pd
breast_ds = pd.read_csv("breast-cancer-wisconsin.csv", sep=',', header=None)

In [232]:
breast_ds_pure = breast_ds.dropna(axis=0)
data = breast_ds_pure.iloc[:,1:]

In [233]:
res = data.iloc[:,-1]
res = res - 3

In [234]:
data.iloc[:,-1] = res

In [238]:
breast_ds_arr = data.values.astype('int')

In [241]:
breast_ds_arr

array([[ 5,  1,  1, ...,  1,  1, -1],
       [ 5,  4,  4, ...,  2,  1, -1],
       [ 3,  1,  1, ...,  1,  1, -1],
       ..., 
       [ 5, 10, 10, ..., 10,  2,  1],
       [ 4,  8,  6, ...,  6,  1,  1],
       [ 4,  8,  8, ...,  4,  1,  1]])

In [102]:
ion = pd.read_csv("ionosphere.csv", sep=',', header=None)
ion_ds_pure = ion.dropna(axis=0)
data = ion_ds_pure.iloc[:,1:]

In [104]:
data.iloc[:,-1] = data.iloc[:,-1].map({'b': -1, 'g': 1})

In [108]:
ion_arr = data.values.astype('float')

In [109]:
ion_arr

array([[  0.00000000e+00,   9.95390000e-01,  -5.88900000e-02, ...,
          1.86410000e-01,  -4.53000000e-01,   1.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,  -1.88290000e-01, ...,
         -1.37380000e-01,  -2.44700000e-02,  -1.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,  -3.36500000e-02, ...,
          5.60450000e-01,  -3.82380000e-01,   1.00000000e+00],
       ..., 
       [  0.00000000e+00,   9.47010000e-01,  -3.40000000e-04, ...,
          9.26970000e-01,  -5.77000000e-03,   1.00000000e+00],
       [  0.00000000e+00,   9.06080000e-01,  -1.65700000e-02, ...,
          8.74030000e-01,  -1.62430000e-01,   1.00000000e+00],
       [  0.00000000e+00,   8.47100000e-01,   1.35330000e-01, ...,
          8.57640000e-01,  -6.15100000e-02,   1.00000000e+00]])

In [113]:
#part 3

In [119]:
#Ionosphere Dataset

In [116]:
VotedPerceptron(ion_arr)

[(array([ 0.     ,  0.99539, -0.05889,  0.85243,  0.02306,  0.83398,
         -0.37708,  1.     ,  0.0376 ,  0.85243, -0.17755,  0.59755,
         -0.44945,  0.60536, -0.38223,  0.84356, -0.38542,  0.58212,
         -0.32192,  0.56971, -0.29674,  0.36946, -0.47357,  0.56811,
         -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,  0.42267,
         -0.54487,  0.18641, -0.453  ]), 1.0, 1),
 (array([ 0.     , -0.00461,  0.1294 , -0.07792,  0.38462,  0.94266,
          0.55889,  0.     ,  0.08309,  0.34369,  0.49988,  0.25323,
          0.24762,  1.12221,  0.59292,  0.78857,  0.23695,  0.25103,
          0.67808,  0.70122,  0.15626,  0.55002, -0.11623,  0.77143,
         -0.24602,  0.61546, -0.27767,  0.40306, -0.22497,  0.58893,
         -0.48199,  0.32379, -0.42853]), 0.0, 6),
 (array([ 0.     , -0.00461,  0.1294 , -0.07792,  0.38462, -0.05734,
          1.55889,  0.     ,  0.08309,  1.34369,  1.49988,  0.25323,
          0.24762,  1.12221,  0.59292, -0.21143, -0.76305,  1.25103,
   

In [118]:
VanillaPerceptron(ion_arr)

(array([ 0.     ,  6.21147, -0.99725,  7.1674 ,  3.92617,  1.30611,
         2.4786 ,  0.98788,  3.49613, -1.46721, -2.57807, -2.21319,
         3.92031,  0.87412, -1.51396,  2.07902,  6.11757,  2.42863,
        -0.08722, -1.64445, -5.69072,  2.65991,  0.40273,  3.79799,
         4.02637, -2.04049, -0.10835, -0.78763,  0.94386,  3.9875 ,
        -2.97007, -0.78712, -4.49583]), -4.0)

In [120]:
#Breast Cancer Dataset

In [121]:
VotedPerceptron(breast_ds_arr)

[(array([-5., -1., -1., -1., -2., -1., -3., -1., -1.]), -1, 5),
 (array([ 3.,  9.,  9.,  7.,  5.,  9.,  6.,  6.,  0.]), 0, 1),
 (array([ 2.,  8.,  8.,  6.,  3., -1.,  3.,  5., -1.]), -1, 1),
 (array([ 0.,  7.,  6.,  5.,  1., -2.,  0.,  4., -2.]), -2, 1),
 (array([-2.,  6.,  5.,  4., -1., -3., -1.,  3., -7.]), -3, 12),
 (array([  5.,   9.,   7.,  14.,   4.,   7.,   4.,   7.,  -3.]), -2, 2),
 (array([  2.,   8.,   6.,  13.,   2.,   6.,   2.,   6.,  -4.]), -3, 2),
 (array([  1.,   7.,   5.,  12.,   0.,   5.,  -1.,   5.,  -5.]), -4, 2),
 (array([ -2.,   5.,   4.,  11.,  -1.,   4.,  -3.,   4.,  -6.]), -5, 2),
 (array([ -4.,   4.,   3.,  10.,  -3.,   3.,  -5.,   3.,  -7.]), -6, 1),
 (array([-5.,  3.,  0.,  9., -5.,  2., -6.,  2., -8.]), -7, 3),
 (array([  5.,  10.,   7.,  12.,   3.,   7.,   1.,   6.,  -5.]), -6, 1),
 (array([  3.,   9.,   6.,  10.,   1.,   6.,  -2.,   5.,  -6.]), -7, 1),
 (array([ 0.,  8.,  4.,  9., -1.,  5., -4.,  4., -7.]), -8, 1),
 (array([-2.,  7.,  3.,  8., -3.,  4., -6

In [122]:
VanillaPerceptron(breast_ds_arr)

(array([  1.62000000e+03,   1.50900000e+03,   1.50300000e+03,
          1.25700000e+03,   1.20100000e+03,  -3.61744630e+07,
          1.34900000e+03,   1.33700000e+03,   5.91000000e+02]), 216)

In [123]:
#Part 4

In [124]:
min_epoch = 5
diff_epoch = 5
max_epoch = 50

In [229]:
def merge_arrays(arr):
    out = np.array([])
    #print out.shape
    for r in arr:
        if r.shape[0]==0:
            pass
        elif out.shape[0]==0:
            out = r
        else:
            out = np.concatenate((out, r), axis=0)
    #print out.shape
    return out

def score(test_real, test_pred):
    total = len(test_real)
    same = 0
    for a in zip(test_real, test_pred):
        if a[0]==a[1]:
            same += 1
    return float(same*1.0/total*1.0)

def voted_perceptron_model(train, test, epoch=1):
    model = VotedPerceptron(train, epoch)
    test_in = np.delete(test, -1, axis=1)
    test_out = []
    for val in test_in:
        pred = predictVoted(model, val)
        test_out.append(pred)
    test_real = test[:,-1]
    return score(test_real, test_out)


def vanilla_perceptron_model(train, test, epoch=1):
    model = VanillaPerceptron(train, epoch)
    test_in = np.delete(test, -1, axis=1)
    test_out = []
    for val in test_in:
        pred = predictVanilla(model, val)
        test_out.append(pred)
    test_real = test[:,-1]
    return score(test_real, test_out)
    

def perceptron_cross_valid(arr, string):
    k = 10
    for i in xrange(min_epoch, max_epoch+1, diff_epoch):
        split_arr = np.asarray(np.array_split(arr, k))
        ans_arr = []
        for j in range(k):
            test_arr = split_arr[j]
            train_arr = merge_arrays(split_arr[:j])
            t = merge_arrays(split_arr[j+1:])
            train_arr = merge_arrays([train_arr,t])
            if string=="voted":
                accuracy = voted_perceptron_model(train_arr, test_arr, i)
            elif string=="vanilla":
                accuracy = vanilla_perceptron_model(train_arr, test_arr, i)
            ans_arr.append(accuracy)
        larr = np.array(ans_arr)
        print ("Epoch {0} -> {1} +/- {2}").format(i, larr.mean(), 2*larr.std())

        


In [230]:
print "--Ionosphere Dataset--"
print "Accuracy of Voted Perceptron"
perceptron_cross_valid(ion_arr, "voted")
print "Accuracy of Vanilla Perceptron"
perceptron_cross_valid(ion_arr, "vanilla")

--Ionosphere Dataset--
Accuracy of Voted Perceptron
Epoch 5 -> 0.832380952381 +/- 0.208342992973
Epoch 10 -> 0.826666666667 +/- 0.192145069911
Epoch 15 -> 0.837936507937 +/- 0.178685043222
Epoch 20 -> 0.840793650794 +/- 0.173346414996
Epoch 25 -> 0.840793650794 +/- 0.173346414996
Epoch 30 -> 0.843650793651 +/- 0.157603941155
Epoch 35 -> 0.843650793651 +/- 0.169579979993
Epoch 40 -> 0.846507936508 +/- 0.165530823458
Epoch 45 -> 0.846507936508 +/- 0.165530823458
Epoch 50 -> 0.843650793651 +/- 0.169579979993
Accuracy of Vanilla Perceptron
Epoch 5 -> 0.832380952381 +/- 0.227808249718
Epoch 10 -> 0.849285714286 +/- 0.207851006291
Epoch 15 -> 0.84373015873 +/- 0.208569797776
Epoch 20 -> 0.849365079365 +/- 0.195924461356
Epoch 25 -> 0.840952380952 +/- 0.196486138751
Epoch 30 -> 0.852222222222 +/- 0.190383310688
Epoch 35 -> 0.863571428571 +/- 0.189138756969
Epoch 40 -> 0.852222222222 +/- 0.190383310688
Epoch 45 -> 0.846587301587 +/- 0.214618260482
Epoch 50 -> 0.849444444444 +/- 0.204999308665


In [223]:
print "--Breast Cancer Dataset--"
print "Accuracy of Voted Perceptron"
perceptron_cross_valid(breast_ds_arr, "voted")
print "Accuracy of Vanilla Perceptron"
perceptron_cross_valid(breast_ds_arr, "vanilla")

--Breast Cancer Dataset--
Accuracy of Voted Perceptron
Epoch 5 -> 0.655445134576 +/- 0.252457204031
Epoch 10 -> 0.655445134576 +/- 0.252457204031
Epoch 15 -> 0.655445134576 +/- 0.252457204031
Epoch 20 -> 0.655445134576 +/- 0.252457204031
Epoch 25 -> 0.655445134576 +/- 0.252457204031
Epoch 30 -> 0.655445134576 +/- 0.252457204031
Epoch 35 -> 0.655445134576 +/- 0.252457204031
Epoch 40 -> 0.655445134576 +/- 0.252457204031
Epoch 45 -> 0.655445134576 +/- 0.252457204031
Epoch 50 -> 0.655445134576 +/- 0.252457204031
Accuracy of Vanilla Perceptron
Epoch 5 -> 0.655445134576 +/- 0.252457204031
Epoch 10 -> 0.655445134576 +/- 0.252457204031
Epoch 15 -> 0.655445134576 +/- 0.252457204031
Epoch 20 -> 0.655445134576 +/- 0.252457204031
Epoch 25 -> 0.655445134576 +/- 0.252457204031
Epoch 30 -> 0.655445134576 +/- 0.252457204031
Epoch 35 -> 0.655445134576 +/- 0.252457204031
Epoch 40 -> 0.655445134576 +/- 0.252457204031
Epoch 45 -> 0.655445134576 +/- 0.252457204031
Epoch 50 -> 0.655445134576 +/- 0.252457204